structure          inputs/mapk_ion.psf
coordinates        inputs/mapk_ion.pdb

paraTypeCharmm     on
parameters         inputs/par_water_ions_ale.prm
parameters         inputs/par_all36_prot.prm
parameters         inputs/par_all36_cgenff.prm

exclude             scaled1-4
1-4scaling          1.0
cutoff              12.0
switching           on
switchdist          10.0
pairlistdist        13.5

timestep            2.0
rigidBonds          all
nonbondedFreq       1
fullElectFrequency  2
stepspercycle       20

PME                 yes
PMEGridSizeX        256
PMEGridSizeY        256
PMEGridSizeZ        256
margin              5

wrapAll             on

GPUresident         on

restartfreq         5000
dcdfreq             5000
xstFreq             5000
outputEnergies      500
outputPressure      500
outputTiming        5000

outputName          runs/01_NVT/MAPK_NVT
set temp            298
firsttimestep       0

cellBasisVector1    122.91 0 0
cellBasisVector2    0 117.13 0
cellBasisVector3    0 0 131.32
cellOrigin          7.90 0.62 -3.46

temperature         $temp

langevin            on
langevinDamping     1
langevinTemp        $temp

langevinPiston      off

minimize            50000
reinitvels          $temp
run                 2500000
