structure          inputs/ADK_ion.psf
coordinates        inputs/ADK_ion.pdb

paraTypeCharmm     on
parameters         inputs/par_water_ions_ale.prm
parameters         inputs/par_all36_prot.prm
parameters         inputs/par_all36_cgenff.prm

exclude             scaled1-4
1-4scaling          1.0
cutoff              12.0
switching           on
switchdist          10.0
pairlistdist        13.5

timestep            2.0
rigidBonds          all
nonbondedFreq       1
fullElectFrequency  2
stepspercycle       20

PME                 yes
PMEGridSizeX        128
PMEGridSizeY        128
PMEGridSizeZ        128
margin              5

wrapAll             on

restartfreq         1000
dcdfreq             1000
xstFreq             1000
outputEnergies      500
outputPressure      500
outputTiming        1000

outputName          runs/01_NVT/ADK_NVT
set temp            298
firsttimestep       0

cellBasisVector1    126.16 0 0
cellBasisVector2    0 118.25 0
cellBasisVector3    0 0 117.03
cellOrigin          73.74 76.31 78.04

temperature         $temp

langevin            on
langevinDamping     1
langevinTemp        $temp

langevinPiston      off

minimize            50000
reinitvels          $temp
run                 5000000
